/**
 * The history index is GENERATED, never hand-maintained.
 *
 * A hand-kept index falls out of date the first time a session ends before
 * updating it, and it is the file a fresh agent trusts most. So ordering lives
 * in the filename, metadata lives in each file's front-matter, and
 * `relay index` derives the index from both. Drift becomes impossible instead
 * of merely discouraged.
 */
import {
  UserError,
  historyFilename,
  nextSeq,
  nowIso,
  paths,
  read,
  readHistory,
  readHistoryOrphans,
  serializeFrontmatter,
  write,
} from "./core.mjs";
import { commitsSince, head, isGitRepo, lastCommitTouching } from "./git.mjs";

export const REQUIRED_FIELDS = ["seq", "agent", "date", "task", "status", "summary", "next"];
export const STATUSES = ["done", "partial", "blocked"];

const isPlaceholder = (v) => typeof v === "string" && v.startsWith("TODO:");

/** The adoption bootstrap entry, if it exists and an agent has not finished it. */
export function bootstrapPending(entries) {
  return (
    entries.find(
      (e) => e.data.bootstrap && (isPlaceholder(e.data.summary) || isPlaceholder(e.data.next)),
    ) || null
  );
}

const HEADER = `# History index

<!-- GENERATED BY \`relay index\` — DO NOT EDIT BY HAND.
     Every row is derived from the front-matter of a file in .relay/history/.
     To change a row, edit that file and re-run \`relay index\`. -->`;

export function buildIndex(root) {
  const entries = readHistory(root);
  const rows = entries.map((e) => {
    const d = e.data || {};
    const date = String(d.date || "").slice(0, 10) || "—";
    const status = d.status || "—";
    const summary = String(d.summary || "").replace(/\|/g, "\\|") || "—";
    const task = d.task || e.task || "—";
    return `| ${String(e.seq).padStart(4, "0")} | ${date} | ${d.agent || e.agent} | \`${task}\` | ${status} | ${summary} | [log](${"history/" + e.file}) |`;
  });

  const body = entries.length
    ? [
        "| Seq | Date | Agent | Task | Status | Summary | Log |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        ...rows,
      ].join("\n")
    : "_No history entries yet._";

  const superseded = entries
    .filter((e) => Array.isArray(e.data?.supersedes) && e.data.supersedes.length)
    .map(
      (e) =>
        `- ${String(e.seq).padStart(4, "0")} supersedes ${e.data.supersedes
          .map((s) => String(s).padStart(4, "0"))
          .join(", ")}`,
    );

  const orphans = readHistoryOrphans(root);

  const sections = [
    HEADER,
    `Entries: **${entries.length}**. Newest last. Read the newest relevant entries before claiming work.`,
    body,
  ];
  if (superseded.length) sections.push(`## Superseded\n\n${superseded.join("\n")}`);
  if (orphans.length) {
    sections.push(
      `## Unreadable files\n\nThese are in \`.relay/history/\` but do not match \`NNNN_agent_task.md\`:\n\n${orphans
        .map((o) => `- \`${o}\``)
        .join("\n")}`,
    );
  }
  // Blank line between sections: a markdown table directly after a paragraph
  // does not render as a table.
  return `${sections.join("\n\n")}\n`;
}

export function writeIndex(root) {
  const content = buildIndex(root);
  write(paths(root).index, content);
  return content;
}

/** True when history.md already matches what `relay index` would produce. */
export function indexIsCurrent(root) {
  const current = read(paths(root).index);
  if (current === null) return false;
  const built = buildIndex(root);
  return normalise(current) === normalise(built);
}

const normalise = (s) => s.replace(/\r\n/g, "\n").trimEnd();

/**
 * Create the next history log. Returns its path.
 *
 * `next` is mandatory on purpose. A handoff log that does not say what the
 * following agent should do next is the most expensive kind of log: it costs a
 * full context rebuild to reach the same conclusion its author already had.
 */
export function createLog(root, opts) {
  const { agent, task, status = "done", session, summary, next, body } = opts;
  if (!agent) throw new UserError("--agent is required.");
  if (!task) throw new UserError("--task is required.");
  if (!STATUSES.includes(status)) {
    throw new UserError(`--status must be one of: ${STATUSES.join(", ")}`);
  }
  const seq = nextSeq(root);
  const file = historyFilename(seq, agent, task);
  const target = `${paths(root).historyDir}/${file}`;

  const front = serializeFrontmatter({
    seq,
    agent,
    session: session || undefined,
    date: nowIso(),
    task,
    status,
    summary: summary || "TODO: one line describing what changed.",
    next: next || "TODO: the single next action for the following agent.",
    supersedes: [],
    git_head: head(root) || undefined,
  });

  write(target, `${front}\n\n${body || template(task)}`);
  return { path: target, file, seq };
}

/**
 * How much work has landed in git without a handoff log.
 *
 * The reference point is the newest commit that included a history log, not
 * the `git_head` recorded inside it: logs are written before the commit that
 * carries the work (agents do not commit unless asked), so that commit would
 * otherwise always count as unlogged. `git_head` is the fallback for projects
 * whose `.relay/` is never committed.
 *
 * Returns `{ git: false }` without a repository, and `count: null` when there
 * is nothing to measure from yet.
 */
export function commitDrift(root) {
  if (!isGitRepo(root)) return { git: false, count: null };
  const logged = lastCommitTouching(root, ".relay/history");
  if (logged) return { git: true, count: commitsSince(root, logged), since: "the last committed log" };
  const withHead = readHistory(root).filter((e) => e.data.git_head);
  if (withHead.length) {
    const last = withHead[withHead.length - 1];
    return { git: true, count: commitsSince(root, String(last.data.git_head)), since: last.file };
  }
  return { git: true, count: null };
}

function template(task) {
  return `# ${task}

## What I did

<!-- Files added, modified, deleted. Decisions and why. Keep it factual. -->

## Commands run and their outcomes

<!-- Exact commands and exact results. "Tests pass" is not an outcome;
     "178 passed / 3 skipped" is. Record failures too. -->

## External resources touched

<!-- IDs, URLs, revisions, queue names. Never credentials or secret values. -->

## Risks, warnings, and what is NOT done

<!-- Anything the next agent would be burned by. Unverified assumptions
     belong here, not in the summary. -->

## Next

<!-- Mirror the \`next:\` front-matter field, with enough detail to act on:
     the exact command, file, or decision that comes next. -->
`;
}
